/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem_informasi_perpustakaan;

import java.awt.Cursor;
import javax.swing.JOptionPane;
import login_admin.login_admin;
import pencarian_buku.Pencarian_buku_option;
import pendaftaran_buku.Daftar_buku_option;
import pendaftaran_member.daftar_member;

/**
 *
 * @author Daniel
 */
//Class untuk Menu Utama
public class Main_menu extends javax.swing.JFrame {
    public static boolean isLoggedIn = false;
    /**
     * Creates new form Main_menu
     */
    public Main_menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        if(isLoggedIn){
            btn_login.setText("Log out");
        }
    }
    public Main_menu(boolean isLoggedIn) {
        this.isLoggedIn = isLoggedIn;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        if(isLoggedIn){
            btn_login.setText("Log Out");
        }
        else{
            btn_login.setText("Log In");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_pendaftaran_buku = new javax.swing.JLabel();
        btn_pencarian_buku = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_login = new javax.swing.JLabel();
        btn_daftar_member = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_pendaftaran_buku.setFont(new java.awt.Font("Harrington", 1, 20)); // NOI18N
        btn_pendaftaran_buku.setForeground(new java.awt.Color(255, 255, 255));
        btn_pendaftaran_buku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_pendaftaran_buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tbh_buku.jpg"))); // NOI18N
        btn_pendaftaran_buku.setText("Pendaftaran Buku");
        btn_pendaftaran_buku.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pendaftaran_buku.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_pendaftaran_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pendaftaran_bukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pendaftaran_bukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pendaftaran_bukuMouseExited(evt);
            }
        });
        getContentPane().add(btn_pendaftaran_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 180, 90));

        btn_pencarian_buku.setFont(new java.awt.Font("Harrington", 1, 20)); // NOI18N
        btn_pencarian_buku.setForeground(new java.awt.Color(255, 255, 255));
        btn_pencarian_buku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_pencarian_buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_cari_buku_50.png"))); // NOI18N
        btn_pencarian_buku.setText("Pencarian Buku");
        btn_pencarian_buku.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_pencarian_buku.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pencarian_buku.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_pencarian_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pencarian_bukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pencarian_bukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pencarian_bukuMouseExited(evt);
            }
        });
        getContentPane().add(btn_pencarian_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 160, 80));

        jLabel1.setFont(new java.awt.Font("Yellowtail", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Home");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 90, 24));

        btn_login.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 0, 51));
        btn_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_login.setText("Log In");
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_loginMouseExited(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 70, -1));

        btn_daftar_member.setFont(new java.awt.Font("Harrington", 1, 20)); // NOI18N
        btn_daftar_member.setForeground(new java.awt.Color(255, 255, 255));
        btn_daftar_member.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_daftar_member.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/daftar_member_50.png"))); // NOI18N
        btn_daftar_member.setText("Daftar Member");
        btn_daftar_member.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_daftar_member.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_daftar_member.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_daftar_member.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_daftar_member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_daftar_memberMouseClicked(evt);
            }
        });
        getContentPane().add(btn_daftar_member, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 150, 80));

        jPanel4.setBackground(new java.awt.Color(148,61,21,70));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(102, 0, 102), new java.awt.Color(0, 0, 255), new java.awt.Color(102, 0, 102)));
        jPanel4.setForeground(new java.awt.Color(163, 9, 9));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 470, 370));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Background600x650.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pendaftaran_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pendaftaran_bukuMouseClicked
        this.dispose();
        if(isLoggedIn){
            Daftar_buku_option daftar_buku_option = new Daftar_buku_option();
            daftar_buku_option.setVisible(true);
        }
        else{
            login_admin lg_admin = new login_admin(0);
            lg_admin.setVisible(true);
        }
    }//GEN-LAST:event_btn_pendaftaran_bukuMouseClicked

    private void btn_pencarian_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pencarian_bukuMouseClicked
        this.dispose();
        Pencarian_buku_option pencarian_buku_option = new Pencarian_buku_option();
        pencarian_buku_option.setVisible(true);
    }//GEN-LAST:event_btn_pencarian_bukuMouseClicked

    private void btn_pendaftaran_bukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pendaftaran_bukuMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_pendaftaran_bukuMouseEntered

    private void btn_pendaftaran_bukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pendaftaran_bukuMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btn_pendaftaran_bukuMouseExited

    private void btn_pencarian_bukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pencarian_bukuMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_pencarian_bukuMouseEntered

    private void btn_pencarian_bukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pencarian_bukuMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btn_pencarian_bukuMouseExited

    private void btn_daftar_memberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_daftar_memberMouseClicked
        // TODO add your handling code here:
        daftar_member df_member = new daftar_member();
        df_member.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_daftar_memberMouseClicked

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
        this.dispose();
        if(isLoggedIn){
            int response = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin log out?", "Konfirmasi Log out", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(response == JOptionPane.YES_OPTION){
                login_admin.id_pegawai_logged_in = 0;
                Main_menu main_menu = new Main_menu(false);
                main_menu.setVisible(true);
            }
        }
        else{
            login_admin lg_admin = new login_admin(1);
            lg_admin.setVisible(true);
        }

    }//GEN-LAST:event_btn_loginMouseClicked

    private void btn_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_loginMouseEntered

    private void btn_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btn_loginMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel btn_daftar_member;
    private javax.swing.JLabel btn_login;
    private javax.swing.JLabel btn_pencarian_buku;
    private javax.swing.JLabel btn_pendaftaran_buku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
