/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendaftaran_buku;

import Report.Report_option;
import denda_buku.daftar_denda;
import denda_buku.daftar_pengembalian_telat;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import peminjaman_pengembalian_buku.List_peminjaman;
import peminjaman_pengembalian_buku.peminjaman_buku;
import peminjaman_pengembalian_buku.pengembalian_buku;
import pencarian_buku.Searching;
import sistem_informasi_perpustakaan.Main_menu;
import sistem_informasi_perpustakaan.connection.db_connection;

/**
 *
 * @author Daniel
 */
//Class yang berisi pilihan menu pada saat melakukan pendaftaran buku
public class Daftar_buku_option extends javax.swing.JFrame {

    /**
     * Creates new form Daftar_buku_option
     */
    public Daftar_buku_option() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    //parameter id isinya id pegawai yang login, nnti bisa dipake untuk yang peminjaman sama pengembalian 
    public Daftar_buku_option(int id) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_buat_laporan = new javax.swing.JLabel();
        btn_daftar_buku = new javax.swing.JLabel();
        btn_edit_buku = new javax.swing.JLabel();
        btn_back = new javax.swing.JLabel();
        btn_peminjaman = new javax.swing.JLabel();
        btn_pengembalian = new javax.swing.JLabel();
        btn_daftar_denda = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_list_peminjaman = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_buat_laporan.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_buat_laporan.setForeground(new java.awt.Color(255, 255, 255));
        btn_buat_laporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_buat_laporan.setText("Buat Laporan");
        btn_buat_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buat_laporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_buat_laporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_buat_laporanMouseExited(evt);
            }
        });
        getContentPane().add(btn_buat_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        btn_daftar_buku.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_daftar_buku.setForeground(new java.awt.Color(255, 255, 255));
        btn_daftar_buku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_daftar_buku.setText("Daftar Buku");
        btn_daftar_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_daftar_bukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_daftar_bukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_daftar_bukuMouseExited(evt);
            }
        });
        getContentPane().add(btn_daftar_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 90, -1));

        btn_edit_buku.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_edit_buku.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit_buku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_edit_buku.setText("Edit Data Buku");
        btn_edit_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_edit_bukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_edit_bukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_edit_bukuMouseExited(evt);
            }
        });
        getContentPane().add(btn_edit_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        btn_back.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_back.setText("Back");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_backMouseExited(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 70, -1));

        btn_peminjaman.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_peminjaman.setForeground(new java.awt.Color(255, 255, 255));
        btn_peminjaman.setText("Peminjaman Buku");
        btn_peminjaman.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_peminjamanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_peminjamanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_peminjamanMouseExited(evt);
            }
        });
        getContentPane().add(btn_peminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        btn_pengembalian.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_pengembalian.setForeground(new java.awt.Color(255, 255, 255));
        btn_pengembalian.setText("Pengembalian Buku");
        btn_pengembalian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pengembalianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pengembalianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pengembalianMouseExited(evt);
            }
        });
        getContentPane().add(btn_pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        btn_daftar_denda.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_daftar_denda.setForeground(new java.awt.Color(255, 255, 255));
        btn_daftar_denda.setText("Daftar Denda");
        btn_daftar_denda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_daftar_denda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_daftar_dendaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_daftar_dendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_daftar_dendaMouseExited(evt);
            }
        });
        getContentPane().add(btn_daftar_denda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 82, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Menu Pegawai");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 24, -1, -1));

        btn_list_peminjaman.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_list_peminjaman.setForeground(new java.awt.Color(255, 255, 255));
        btn_list_peminjaman.setText("List Peminjaman");
        btn_list_peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_list_peminjamanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_list_peminjamanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_list_peminjamanMouseExited(evt);
            }
        });
        getContentPane().add(btn_list_peminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg_daftar_buku_option.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tampil_notif(){
        String tgl = null;
        LocalDate tgl_kembali;
        LocalDate tgl_sekarang;
        int jml_telat = 0;
        
        Connection conn = db_connection.getConnection();
        PreparedStatement ps;
        ResultSet rs;
        String sql;
        
        sql ="SELECT tb_peminjaman.tgl_kembali FROM tb_peminjaman\n" +
                "INNER JOIN tb_member ON tb_peminjaman.`member_id`=tb_member.`id`\n" +
                "WHERE NOT EXISTS (SELECT tb_pengembalian.`id` FROM tb_pengembalian\n" +
                "WHERE tb_peminjaman.`id` = tb_pengembalian.`id`);";
        
        Date tanggal = new Date();
        SimpleDateFormat dateNow = new SimpleDateFormat("yyy-MM-dd");//menentukan format tanggal (tahun-bulan-hari)
        String nowDate = dateNow.format(tanggal);// menyimpan tanggal sekarang ke dalam variabel yg bertipe string
        
        try {
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                tgl= rs.getString(1);
                tgl_kembali = LocalDate.parse(tgl, DateTimeFormatter.ISO_DATE);
                tgl_sekarang = LocalDate.parse(nowDate, DateTimeFormatter.ISO_DATE);
                if (tgl_sekarang.isAfter(tgl_kembali)) {
                    jml_telat++;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(daftar_denda.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(jml_telat>0){
            int respon = JOptionPane.showConfirmDialog(this, "Ada "+ jml_telat +" pengembalian pinjaman yang terlambat.\nMau lihat?", "Pengembalian Terlambat", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if(respon==JOptionPane.YES_OPTION){
                daftar_pengembalian_telat kembali = new daftar_pengembalian_telat();
                kembali.setVisible(true);
                this.dispose();
            }
            
            if(respon==JOptionPane.NO_OPTION){
                //code untuk ke jFrame pengembalian
                pengembalian_buku Pengembalian = new pengembalian_buku();
                Pengembalian.setVisible(true);
                this.dispose();
            }
        }
        jml_telat=0;
    }
    
    private void btn_daftar_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_daftar_bukuMouseClicked
        this.dispose();
        Tipe_buku_option tipe_buku_option = new Tipe_buku_option(0,4);
        tipe_buku_option.setVisible(true);
    }//GEN-LAST:event_btn_daftar_bukuMouseClicked

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        this.dispose();
        Main_menu main_menu = new Main_menu();
        main_menu.setVisible(true);
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_edit_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_bukuMouseClicked
        this.dispose();
        Tipe_buku_option tipe_buku_option = new Tipe_buku_option(2, 0);
        tipe_buku_option.setVisible(true);
    }//GEN-LAST:event_btn_edit_bukuMouseClicked

    private void btn_daftar_bukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_daftar_bukuMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_daftar_bukuMouseEntered

    private void btn_daftar_bukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_daftar_bukuMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btn_daftar_bukuMouseExited

    private void btn_edit_bukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_bukuMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_edit_bukuMouseEntered

    private void btn_edit_bukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_bukuMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btn_edit_bukuMouseExited

    private void btn_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_backMouseEntered

    private void btn_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btn_backMouseExited

    private void btn_peminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_peminjamanMouseClicked
        peminjaman_buku pinjam = new peminjaman_buku();
        pinjam.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_peminjamanMouseClicked

    private void btn_daftar_dendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_daftar_dendaMouseClicked
        // TODO add your handling code here:
        daftar_denda daftarDenda = new daftar_denda();
        daftarDenda.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_daftar_dendaMouseClicked

    private void btn_pengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengembalianMouseClicked
        // TODO add your handling code here:
        tampil_notif();
    }//GEN-LAST:event_btn_pengembalianMouseClicked

    private void btn_buat_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buat_laporanMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Report_option report_option = new Report_option();
        report_option.setVisible(true);
    }//GEN-LAST:event_btn_buat_laporanMouseClicked

    private void btn_list_peminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_list_peminjamanMouseClicked
        this.dispose();
        List_peminjaman list_peminjaman = new List_peminjaman();
        list_peminjaman.setVisible(true);
    }//GEN-LAST:event_btn_list_peminjamanMouseClicked

    private void btn_buat_laporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buat_laporanMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_buat_laporanMouseEntered

    private void btn_daftar_dendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_daftar_dendaMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_daftar_dendaMouseEntered

    private void btn_pengembalianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengembalianMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_pengembalianMouseEntered

    private void btn_peminjamanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_peminjamanMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_peminjamanMouseEntered

    private void btn_list_peminjamanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_list_peminjamanMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_list_peminjamanMouseEntered

    private void btn_buat_laporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buat_laporanMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btn_buat_laporanMouseExited

    private void btn_daftar_dendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_daftar_dendaMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btn_daftar_dendaMouseExited

    private void btn_pengembalianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pengembalianMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btn_pengembalianMouseExited

    private void btn_peminjamanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_peminjamanMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btn_peminjamanMouseExited

    private void btn_list_peminjamanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_list_peminjamanMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btn_list_peminjamanMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar_buku_option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Daftar_buku_option().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_buat_laporan;
    private javax.swing.JLabel btn_daftar_buku;
    private javax.swing.JLabel btn_daftar_denda;
    private javax.swing.JLabel btn_edit_buku;
    private javax.swing.JLabel btn_list_peminjaman;
    private javax.swing.JLabel btn_peminjaman;
    private javax.swing.JLabel btn_pengembalian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
