/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Tag;

import java.awt.Cursor;
import pencarian_buku.Tag_search;
import pendaftaran_buku.Daftar_buku;
import pendaftaran_buku.Daftar_journal;
import pendaftaran_buku.Daftar_majalah;

/**
 *
 * @author Daniel
 */
//Class yang akan memunculkan list tag yang ada.Ketika tombol submit di click akan mengubah isi dari textbox tag
public class Tag_list extends javax.swing.JFrame {
    private Daftar_buku daftar_buku;
    private Tag_search tag_search;
    private Daftar_journal daftar_journal;
    private Daftar_majalah daftar_majalah;
    private int from;//variable untuk menandakan dari mana form ini dibuka (daftar_buku atau tag_search) daftar_buku : 0 tag_search : 1
    private int tag_num;//tag ke-berapa yang akan diganti valuenya
    /** Creates new form Tag_list
     * @param daftar_buku */
    //constructor yang dipanggil kalau form dibuka dari pendaftaran buku
    public Tag_list(Daftar_buku daftar_buku,int tag_num) {
        this.from = 0;
        this.daftar_buku = daftar_buku;
        this.tag_num = tag_num;
        initComponents();
        this.setLocationRelativeTo(this.daftar_buku);
        this.setResizable(false);
    }
    //constructor yang dipanggil kalau forrm dibuka dari pencarian buku (search by tag)
    public Tag_list(Tag_search tag_search,int tag_num) {
        this.from = 1;
        this.tag_search = tag_search;
        this.tag_num = tag_num;
        initComponents();
        this.setLocationRelativeTo(this.tag_search);
        this.setResizable(false);
    }
    public Tag_list(Daftar_journal daftar_journal,int tag_num) {
        this.from = 2;
        this.daftar_journal = daftar_journal;
        this.tag_num = tag_num;
        initComponents();
        this.setLocationRelativeTo(this.tag_search);
        this.setResizable(false);
    }
    public Tag_list(Daftar_majalah daftar_majalah,int tag_num) {
        this.from = 3;
        this.daftar_majalah = daftar_majalah;
        this.tag_num = tag_num;
        initComponents();
        this.setLocationRelativeTo(this.tag_search);
        this.setResizable(false);
    }
    public Tag_list() {
        initComponents();
        this.setResizable(false);
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btn_submit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setBackground(new java.awt.Color(148, 61, 21));
        jList1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Romance", "Sci-Fi", "Fantasy", "Horror", "Mystery", "Historical", "Biography", "Cooking", "Business", "Comedy", "Detective", "Adventure", "Teen", "Children", "Art & Photography", "Personal Development", "Motivational", "Health & Fitness", "Crafts & Hobbies", "Families & Relationship", "Law & Criminology", "Politics & Social Science", "Religion & Spirituality", "Education", "Travel", "Novel", "Comic", "Encyclopedia", "Dictionary", "SMA", "SMP", "SD", "Math", "Biology", "Computer", "Chemistry", "Geography", "Physical Education", "Music", "Civics", "English", "Bahasa Indonesia", "Physics", "Entrepreneurship", "Folktale", "None" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 180, 232));

        btn_submit.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        btn_submit.setForeground(new java.awt.Color(255, 255, 0));
        btn_submit.setText("Submit");
        btn_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_submitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_submitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_submitMouseExited(evt);
            }
        });
        getContentPane().add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        jLabel1.setFont(new java.awt.Font("Harrington", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Tag List");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Background500x400.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//dijalankan kalau button submit ditekan
    private void btn_submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseClicked
        String tag = getTag();
        int tag_ID;
        //pengecekan kalau isinya none textbox nya dikosongkan
        if(tag.equals("None")){
            tag_ID = 0;
            tag = "";
        }
        else{
            tag_ID = getTagID() + 1;
        }
        if(from == 0){
            switch (tag_num) {
                case 1:
                    daftar_buku.textbox_tag1.setText(tag);
                    daftar_buku.idTag1 = tag_ID;
                    break;
                case 2:
                    daftar_buku.textbox_tag2.setText(tag);
                    daftar_buku.idTag2 = tag_ID;
                    break;
                case 3:
                    daftar_buku.textbox_tag3.setText(tag);
                    daftar_buku.idTag3 = tag_ID;
                    break;
                default:
                    break;
            }
            if(daftar_buku.isTagListOpen){
                daftar_buku.isTagListOpen = false;
            }
        }
        else if(from == 1){
            switch (tag_num) {
                case 1:
                    tag_search.textbox_tag1.setText(tag);
                    tag_search.idTag1 = tag_ID;
                    break;
                case 2:
                    tag_search.textbox_tag2.setText(tag);
                    tag_search.idTag2 = tag_ID;
                    break;
                case 3:
                    tag_search.textbox_tag3.setText(tag);
                    tag_search.idTag3 = tag_ID;
                    break;
                default:
                    break;
            }
            if(tag_search.isTagListOpen){
                tag_search.isTagListOpen = false;
            }
        }
        else if(from == 2){
            switch (tag_num) {
                case 1:
                    daftar_journal.textbox_tag1.setText(tag);
                    daftar_journal.idTag1 = tag_ID;
                    break;
                case 2:
                    daftar_journal.textbox_tag2.setText(tag);
                    daftar_journal.idTag2 = tag_ID;
                    break;
                case 3:
                    daftar_journal.textbox_tag3.setText(tag);
                    daftar_journal.idTag3 = tag_ID;
                    break;
                default:
                    break;
            }
            if(daftar_journal.isTagListOpen){
                daftar_journal.isTagListOpen = false;
            }
        }
        else if(from == 3){
            switch (tag_num) {
                case 1:
                    daftar_majalah.textbox_tag1.setText(tag);
                    daftar_majalah.idTag1 = tag_ID;
                    break;
                case 2:
                    daftar_majalah.textbox_tag2.setText(tag);
                    daftar_majalah.idTag2 = tag_ID;
                    break;
                case 3:
                    daftar_majalah.textbox_tag3.setText(tag);
                    daftar_majalah.idTag3 = tag_ID;
                    break;
                default:
                    break;
            }
            if(daftar_majalah.isTagListOpen){
                daftar_majalah.isTagListOpen = false;
            }
        }
        this.dispose();
    }//GEN-LAST:event_btn_submitMouseClicked

    private void btn_submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_submitMouseEntered

    private void btn_submitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btn_submitMouseExited
    //getter and setter
    private String getTag(){
        String tag = (String)jList1.getSelectedValue();
        return tag;
    }
    private int getTagID(){
        int tag_ID = jList1.getSelectedIndex();
        return tag_ID;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tag_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tag_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tag_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tag_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tag_list().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
