/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pencarian_buku;

import Tag.Tag_list;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import sistem_informasi_perpustakaan.connection.db_connection;

/**
 *
 * @author Daniel
 */
//Class yang digunakan kalau melakukan searching berrdasarkan tags buku
public class Tag_search extends javax.swing.JFrame {
    public boolean isTagListOpen = false;//variabel yang membantu agar tag list tidak dibuka lebih dari 1 sebelum menutupnya
    public int idTag1 = 0;
    public int idTag2 = 0;
    public int idTag3 = 0;
    
    /**
     * Creates new form Tag_search
     */
    public Tag_search() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textbox_tag1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textbox_tag2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textbox_tag3 = new javax.swing.JTextField();
        btn_add_tag1 = new javax.swing.JLabel();
        btn_add_tag2 = new javax.swing.JLabel();
        btn_add_tag3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_buku = new javax.swing.JTable();
        btn_search = new javax.swing.JLabel();
        btn_back = new javax.swing.JLabel();
        validasi_tag = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tag 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 41, 46, -1));

        textbox_tag1.setBackground(new java.awt.Color(204, 204, 204));
        textbox_tag1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(textbox_tag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 43, 105, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tag 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 74, 46, -1));

        textbox_tag2.setBackground(new java.awt.Color(204, 204, 204));
        textbox_tag2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        textbox_tag2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textbox_tag2MouseClicked(evt);
            }
        });
        getContentPane().add(textbox_tag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 76, 105, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tag 3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 107, 46, -1));

        textbox_tag3.setBackground(new java.awt.Color(204, 204, 204));
        textbox_tag3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        textbox_tag3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textbox_tag3MouseClicked(evt);
            }
        });
        getContentPane().add(textbox_tag3, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 109, 105, -1));

        btn_add_tag1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_add_tag1.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_tag1.setText("Add tag");
        btn_add_tag1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_add_tag1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_add_tag1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_add_tag1MouseExited(evt);
            }
        });
        getContentPane().add(btn_add_tag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 41, 64, -1));

        btn_add_tag2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_add_tag2.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_tag2.setText("Add tag");
        btn_add_tag2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_add_tag2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_add_tag2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_add_tag2MouseExited(evt);
            }
        });
        getContentPane().add(btn_add_tag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 74, 64, -1));

        btn_add_tag3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_add_tag3.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_tag3.setText("Add tag");
        btn_add_tag3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_add_tag3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_add_tag3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_add_tag3MouseExited(evt);
            }
        });
        getContentPane().add(btn_add_tag3, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 107, 64, -1));

        tabel_buku.setBackground(new java.awt.Color(204, 204, 204));
        tabel_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Judul", "Penulis", "Penerbit", "Tahun Terbit", "Nomor Rak", "Status"
            }
        ));
        jScrollPane1.setViewportView(tabel_buku);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 161, 548, 127));

        btn_search.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_search.setForeground(new java.awt.Color(0, 0, 255));
        btn_search.setText("Search");
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_searchMouseExited(evt);
            }
        });
        getContentPane().add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 135, 60, -1));

        btn_back.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Back");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_backMouseExited(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 135, -1, -1));

        validasi_tag.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        validasi_tag.setForeground(new java.awt.Color(255, 0, 0));
        validasi_tag.setText("Warning !");
        validasi_tag.setVisible(false);
        getContentPane().add(validasi_tag, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 135, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pencarian Dengan Tag");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 11, 210, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg_pencarian_op.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add_tag1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add_tag1MouseClicked
        if(!isTagListOpen){
            Tag_list tag = new Tag_list(this,1);
            tag.setVisible(true);
            isTagListOpen = true;
        }
    }//GEN-LAST:event_btn_add_tag1MouseClicked

    private void textbox_tag2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textbox_tag2MouseClicked
        
    }//GEN-LAST:event_textbox_tag2MouseClicked

    private void textbox_tag3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textbox_tag3MouseClicked
        
    }//GEN-LAST:event_textbox_tag3MouseClicked

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        boolean isValid = tagValidation();
        if(!isValid){
            if(idTag1 == 0 && idTag2 == 0 && idTag3 == 0){
                validasi_tag.setText("Tag minimal ada 1");
            }
            else{
                validasi_tag.setText("Tag tidak boleh sama");
            }
            validasi_tag.setVisible(true);
        }
        else{
            validasi_tag.setVisible(false);
        }
        if(isValid){
            search();
        }
    }//GEN-LAST:event_btn_searchMouseClicked

    private void btn_add_tag2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add_tag2MouseClicked
        if(!isTagListOpen){
            Tag_list tag = new Tag_list(this,2);
            tag.setVisible(true);
            isTagListOpen = true;
        }
    }//GEN-LAST:event_btn_add_tag2MouseClicked

    private void btn_add_tag3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add_tag3MouseClicked
        if(!isTagListOpen){
            Tag_list tag = new Tag_list(this,3);
            tag.setVisible(true);
            isTagListOpen = true;
        }
    }//GEN-LAST:event_btn_add_tag3MouseClicked

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        this.dispose();
        Pencarian_buku_option pencarian_buku_option = new Pencarian_buku_option();
        pencarian_buku_option.setVisible(true);
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_add_tag1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add_tag1MouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_add_tag1MouseEntered

    private void btn_add_tag1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add_tag1MouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btn_add_tag1MouseExited

    private void btn_add_tag2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add_tag2MouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_add_tag2MouseEntered

    private void btn_add_tag2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add_tag2MouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btn_add_tag2MouseExited

    private void btn_add_tag3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add_tag3MouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_add_tag3MouseEntered

    private void btn_add_tag3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add_tag3MouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btn_add_tag3MouseExited

    private void btn_searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_searchMouseEntered

    private void btn_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btn_searchMouseExited

    private void btn_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_backMouseEntered

    private void btn_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btn_backMouseExited
    private boolean tagValidation(){
        if(((idTag1 != idTag2)&&(idTag1 != 0 && idTag2 != 0)) || 
           ((idTag1 != idTag3)&&(idTag1 != 0 && idTag3 != 0)) || 
           ((idTag2 != idTag3)&&(idTag2 != 0 && idTag3 != 0))){
            if((idTag1 != idTag2)&&(idTag1 == idTag3)||(idTag2 == idTag3)){
                return false;
            }
            else if((idTag1 != idTag3)&&(idTag1 == idTag2)){
                return false;
            }
            return true;
        }
        else if(idTag1 != 0 && (idTag2 == 0 && idTag3 == 0)){
            return true;
        }
        else if(idTag2 != 0 && (idTag1 == 0 && idTag3 == 0)){
            return true;
        }
        else if(idTag3 != 0 && (idTag1 == 0 && idTag2 == 0)){
            return true;
        }
        else{
            return false;
        } 
    }
    //proses search
    private void search(){
        String t_judul;
        String t_penulis;
        String t_penerbit;
        int t_thn_terbit;
        int t_no_rak;
        int t_jumlah;
        int t_dipinjam;
        String t_status;
        int t_id_buku;
        Connection conn = db_connection.getConnection();
        PreparedStatement ps = null;
        ResultSet rs = null;
        PreparedStatement ps2 = null;
        ResultSet rs2 = null;
        //untuk setiap id tag yang dipilih akan ditambahkan ke array list
        ArrayList<Integer> tag_id = new ArrayList<Integer>();
        int size;
        String sql = null;
        if(idTag1 != 0){
            tag_id.add(idTag1);
        }
        if(idTag2 != 0){
            tag_id.add(idTag2);
        }
        if(idTag3 != 0){
            tag_id.add(idTag3);
        }
        size = tag_id.size();
        //proses select sesuai banyak tag di dalam array list
        if(size == 1){
            sql = "SELECT tb_tag_buku.buku_id,tb_buku.judul,tb_penulis.nama,tb_penerbit.nama,tb_buku.tahun_terbit,tb_buku.jumlah,tb_rak.no_rak FROM tb_tag_buku INNER JOIN tb_buku ON tb_tag_buku.buku_id = tb_buku.id INNER JOIN tb_penulis ON tb_buku.penulis_id = tb_penulis.id INNER JOIN tb_penerbit ON tb_buku.penerbit_id = tb_penerbit.id INNER JOIN tb_rak ON tb_buku.rak_id = tb_rak.id WHERE tb_tag_buku.tag_id IN(?) GROUP BY tb_tag_buku.buku_id HAVING COUNT(*) = 1;";
        }
        else if(size == 2){
            sql = "SELECT tb_tag_buku.buku_id,tb_buku.judul,tb_penulis.nama,tb_penerbit.nama,tb_buku.tahun_terbit,tb_buku.jumlah,tb_rak.no_rak FROM tb_tag_buku INNER JOIN tb_buku ON tb_tag_buku.buku_id = tb_buku.id INNER JOIN tb_penulis ON tb_buku.penulis_id = tb_penulis.id INNER JOIN tb_penerbit ON tb_buku.penerbit_id = tb_penerbit.id INNER JOIN tb_rak ON tb_buku.rak_id = tb_rak.id WHERE tb_tag_buku.tag_id IN(?,?) GROUP BY tb_tag_buku.buku_id HAVING COUNT(*) = 2;";
        }
        else if(size == 3){
            sql ="SELECT tb_tag_buku.buku_id,tb_buku.judul,tb_penulis.nama,tb_penerbit.nama,tb_buku.tahun_terbit,tb_buku.jumlah,tb_rak.no_rak FROM tb_tag_buku INNER JOIN tb_buku ON tb_tag_buku.buku_id = tb_buku.id INNER JOIN tb_penulis ON tb_buku.penulis_id = tb_penulis.id INNER JOIN tb_penerbit ON tb_buku.penerbit_id = tb_penerbit.id INNER JOIN tb_rak ON tb_buku.rak_id = tb_rak.id WHERE tb_tag_buku.tag_id IN(?,?,?) GROUP BY tb_tag_buku.buku_id HAVING COUNT(*) = 3;";
        }
        String sql2 = "SELECT COUNT(tb_detail_peminjaman.id) FROM tb_detail_peminjaman WHERE buku_id = ? AND status_buku ='dipinjam';";
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Judul");
        tableModel.addColumn("Penulis");
        tableModel.addColumn("Penerbit");
        tableModel.addColumn("Tahun Terbit");
        tableModel.addColumn("Nomor Rak");
        tableModel.addColumn("Status");
        try {
            ps = conn.prepareStatement(sql);
            if(size == 1){
                ps.setInt(1,tag_id.get(0));
            }
            else if(size == 2){
                ps.setInt(1,tag_id.get(0));
                ps.setInt(2,tag_id.get(1));
            }
            else if(size == 3){
                ps.setInt(1,tag_id.get(0));
                ps.setInt(2,tag_id.get(1));
                ps.setInt(3,tag_id.get(2));
            }
            rs = ps.executeQuery();
            while(rs.next()){
                t_id_buku = rs.getInt(1);
                t_judul = rs.getString(2);
                t_penulis = rs.getString(3);
                t_penerbit = rs.getString(4);
                t_thn_terbit = rs.getInt(5);
                t_jumlah = rs.getInt(6);
                t_no_rak = rs.getInt(7);
                ps2 = conn.prepareStatement(sql2);
                ps2.setInt(1,t_id_buku);
                rs2 = ps2.executeQuery();
                if(rs2.next()){
                    t_dipinjam = rs2.getInt(1);
                    t_jumlah = t_jumlah - t_dipinjam;
                }
                if(t_jumlah > 0){
                    t_status = "Tersedia";
                }
                else{
                    t_status = "Sedang Dipinjam";
                }
                tableModel.addRow(new Object[]{
                    t_judul,t_penulis,t_penerbit,t_thn_terbit,t_no_rak,t_status
                });
            }
        } catch (SQLException e) {
        }
        finally{
            if(rs != null){
                try {
                    rs.close();
                } catch (SQLException e) {
                }
            }
            if(rs2 != null){
                try {
                    rs2.close();
                } catch (SQLException e) {
                }
            }
            if(ps != null){
                try {
                    ps.close();
                } catch (SQLException e) {
                }
            }
            if(ps2 != null){
                try {
                    ps2.close();
                } catch (SQLException e) {
                }
            }
            if(conn != null){
                try {
                    conn.close();
                } catch (SQLException e) {
                }
            }
        }
        tabel_buku.setModel(tableModel);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tag_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tag_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tag_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tag_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tag_search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_add_tag1;
    private javax.swing.JLabel btn_add_tag2;
    private javax.swing.JLabel btn_add_tag3;
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_buku;
    public javax.swing.JTextField textbox_tag1;
    public javax.swing.JTextField textbox_tag2;
    public javax.swing.JTextField textbox_tag3;
    private javax.swing.JLabel validasi_tag;
    // End of variables declaration//GEN-END:variables
}
